#!/usr/bin/env sh
# Select vertical offsets for the named Mainte layout sections.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

if [ -r "$SCRIPT_DIR/mainte.local" ]; then
    # shellcheck disable=SC1090
    . "$SCRIPT_DIR/mainte.local"
fi

usage() {
    printf '%s\n' \
        'Usage: ./mainte-layout.sh [--reset]' \
        '' \
        'Select a section, then move it up/down in 10-pixel steps.' \
        'Choose n to enter an exact offset in pixels; positive values move down.'
}

LAYOUT_FILE=${MAINTE_LAYOUT_FILE:-$SCRIPT_DIR/mainte.layout}
case "$LAYOUT_FILE" in
    "~/"*) LAYOUT_FILE=$HOME/${LAYOUT_FILE#~/} ;;
    /*) ;;
    *) LAYOUT_FILE=$SCRIPT_DIR/$LAYOUT_FILE ;;
esac

if [ -r "$LAYOUT_FILE" ]; then
    # shellcheck disable=SC1090
    . "$LAYOUT_FILE"
fi

normalize_offset() {
    value=$1
    if awk -v value="$value" 'BEGIN { exit !(value ~ /^[-+]?[0-9]+$/) }'; then
        awk -v value="$value" 'BEGIN { printf "%.0f\n", value + 0 }'
    else
        printf '%s\n' 0
    fi
}

identity_y=$(normalize_offset "${MAINTE_LAYOUT_IDENTITY_Y:-0}")
graphics_y=$(normalize_offset "${MAINTE_LAYOUT_GRAPHICS_Y:-0}")
locale_y=$(normalize_offset "${MAINTE_LAYOUT_LOCALE_Y:-0}")
performance_y=$(normalize_offset "${MAINTE_LAYOUT_PERFORMANCE_Y:-0}")
memory_y=$(normalize_offset "${MAINTE_LAYOUT_MEMORY_Y:-0}")
network_y=$(normalize_offset "${MAINTE_LAYOUT_NETWORK_Y:-0}")
battery_y=$(normalize_offset "${MAINTE_LAYOUT_BATTERY_Y:-0}")
storage_y=$(normalize_offset "${MAINTE_LAYOUT_STORAGE_Y:-0}")

reset_offsets() {
    identity_y=0
    graphics_y=0
    locale_y=0
    performance_y=0
    memory_y=0
    network_y=0
    battery_y=0
    storage_y=0
}

get_offset() {
    case "$1" in
        1) printf '%s\n' "$identity_y" ;;
        2) printf '%s\n' "$graphics_y" ;;
        3) printf '%s\n' "$locale_y" ;;
        4) printf '%s\n' "$performance_y" ;;
        5) printf '%s\n' "$memory_y" ;;
        6) printf '%s\n' "$network_y" ;;
        7) printf '%s\n' "$battery_y" ;;
        8) printf '%s\n' "$storage_y" ;;
    esac
}

set_offset() {
    case "$1" in
        1) identity_y=$2 ;;
        2) graphics_y=$2 ;;
        3) locale_y=$2 ;;
        4) performance_y=$2 ;;
        5) memory_y=$2 ;;
        6) network_y=$2 ;;
        7) battery_y=$2 ;;
        8) storage_y=$2 ;;
    esac
}

save_layout() {
    layout_dir=$(dirname -- "$LAYOUT_FILE")
    mkdir -p "$layout_dir"
    temporary_file="$LAYOUT_FILE.tmp.$$"
    {
        printf '%s\n' '# Generated by mainte-layout.sh; positive values move a section down.'
        printf 'MAINTE_LAYOUT_IDENTITY_Y=%s\n' "$identity_y"
        printf 'MAINTE_LAYOUT_GRAPHICS_Y=%s\n' "$graphics_y"
        printf 'MAINTE_LAYOUT_LOCALE_Y=%s\n' "$locale_y"
        printf 'MAINTE_LAYOUT_PERFORMANCE_Y=%s\n' "$performance_y"
        printf 'MAINTE_LAYOUT_MEMORY_Y=%s\n' "$memory_y"
        printf 'MAINTE_LAYOUT_NETWORK_Y=%s\n' "$network_y"
        printf 'MAINTE_LAYOUT_BATTERY_Y=%s\n' "$battery_y"
        printf 'MAINTE_LAYOUT_STORAGE_Y=%s\n' "$storage_y"
    } > "$temporary_file"
    mv "$temporary_file" "$LAYOUT_FILE"
    printf 'Saved layout offsets to %s\n' "$LAYOUT_FILE"
}

case "${1:-}" in
    --help)
        usage
        exit 0
        ;;
    --reset)
        reset_offsets
        save_layout
        exit 0
        ;;
    '') ;;
    *)
        printf 'Unknown option: %s\n' "$1" >&2
        usage >&2
        exit 2
        ;;
esac

while :; do
    printf '\nMainte layout offsets (positive = down, negative = up)\n'
    printf '  1) Identity      %s px\n' "$identity_y"
    printf '  2) Graphics      %s px\n' "$graphics_y"
    printf '  3) Locale        %s px\n' "$locale_y"
    printf '  4) Performance   %s px\n' "$performance_y"
    printf '  5) Memory        %s px\n' "$memory_y"
    printf '  6) Network       %s px\n' "$network_y"
    printf '  7) Battery       %s px\n' "$battery_y"
    printf '  8) Storage       %s px\n' "$storage_y"
    printf '  r) Reset all     q) Save and quit\n'
    printf 'Select section: '
    if ! IFS= read -r section; then
        printf '\n'
        exit 1
    fi

    case "$section" in
        q|Q)
            save_layout
            exit 0
            ;;
        r|R)
            reset_offsets
            ;;
        1|2|3|4|5|6|7|8)
            current=$(get_offset "$section")
            printf 'Current offset is %s px. [u]p 10, [d]own 10, [n]ew, [c]ancel: ' "$current"
            if ! IFS= read -r action; then
                printf '\n'
                exit 1
            fi
            case "$action" in
                u|U) new_offset=$((current - 10)) ;;
                d|D) new_offset=$((current + 10)) ;;
                n|N)
                    printf 'Enter offset in pixels: '
                    if ! IFS= read -r requested_offset; then
                        printf '\n'
                        exit 1
                    fi
                    if ! awk -v value="$requested_offset" 'BEGIN { exit !(value ~ /^[-+]?[0-9]+$/) }'; then
                        printf '%s\n' 'Offset must be an integer.' >&2
                        continue
                    fi
                    new_offset=$(normalize_offset "$requested_offset")
                    ;;
                c|C|'') continue ;;
                *)
                    printf '%s\n' 'Choose u, d, n, or c.' >&2
                    continue
                    ;;
            esac
            set_offset "$section" "$new_offset"
            ;;
        *)
            printf '%s\n' 'Choose a section from 1 to 8, r, or q.' >&2
            ;;
    esac
done
